
 
		</div>
	<footer>
		<div id="currency-selector">
			<label>Show Prices In: <select id="currencychoice">
				<?php foreach (History::$currencies as $currency) { ?>
					<option value="<?php echo $currency ?>"<?php echo $this->cc == $currency ? ' selected' : '' ?>><?php

						if ($currency == History::CURRENCY_SE) {
							echo 'EU Tier 1';
						}
						elseif ($currency == History::CURRENCY_NO) {
							echo 'EU Tier 2';
						}
						else {
							echo strtoupper($currency);
						} 

					?> (<?php echo formatCurrency(1.42, $currency) ?>)</option>
				<?php } ?>
			</select></label>
			(<a target="_blank" href="http://steamunpowered.eu/european-tiers/">EU Tiers?</a>)
		</div>
		<p>2010 - <?php echo date('Y') ?> &copy; <a href="http://jrm.cc">Jeff Minard</a></p>
		<p id="saslogon">SteamAlerts.com: Find a game. Set your price. Get an email when the game drops below your price. Never miss a good <a href="http://store.steampowered.com/">Steam</a> deal again!</p>

		<div id="socialwidgets">
			<div id="follow">
				<a href="http://twitter.com/steamalerts_<?php echo $this->cc ?>"
				   class="twitter-follow-button"
				   data-button="grey"
				   data-text-color="#FFFFFF"
				   data-link-color="#00AEFF">Follow @steamalerts_<?php echo $this->cc ?></a>
			</div>
			<div id="tweetit">
				<a href="http://twitter.com/share"
				   class="twitter-share-button"
				   data-url="http://steamalerts.com"
				   data-text="Don't miss a good sale on Steam again, get email alerts for the price you're willing to pay!"
				   data-count="horizontal"
				   data-via="steamalerts">Tweet</a>
			</div>
			<div id="fbLike">
				<div id="fb-root"></div>
				<fb:like href="http://steamalerts.com"
						 send="false"
						 width="300"
						 show_faces="true"
						 colorscheme="dark"
						 font="verdana"></fb:like>
			</div>
		</div>
		<script type="text/javascript">
			window.fbAsyncInit = function() {
				FB.init({
					//appId  : 'YOUR APP ID',
					status : true, // check login status
					cookie : true, // enable cookies to allow the server to access the session
					xfbml  : true  // parse XFBML
				});
			};
			(function() {
				var e = document.createElement('script');
				e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
				e.async = true;
				document.getElementById('fb-root').appendChild(e);
			}());
		</script>
		<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

	</footer>
	</div><?php // end of #container ?>

	<script src="/js/script.js"></script>
	<script src="/js/dygraph-combined.js"></script>

<?php /*	<!--[if lt IE 7 ]>
	<script src="/js/libs/dd_belatedpng.js"></script>
	<script>DD_belatedPNG.fix("img, .png_bg"); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
	<![endif]--> */ ?>

	<script>
		var _gaq=[["_setAccount","UA-99347-7"],["_trackPageview"]];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
		g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
		s.parentNode.insertBefore(g,s)}(document,"script"));
	</script>

	<script src="/js/games.<?php echo $this->cc ?>.js?v=<?php echo $this->mostrecentuid ?>"></script>

</body> 
</html>