<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta charset="utf-8">

	<title><?php

        $title = defined('TITLE') ? TITLE : 'Tumblite';
        echo isset($this->title) ? $this->title . ' -- ' . TITLE : TITLE;

    ?></title>

	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="<?php echo $this->metaDesc ?>" />
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

	<link rel="stylesheet" href="/css/style.css">

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js"></script>
	<script>window.jQuery || document.write("<script src='/js/libs/jquery-1.5.1.min.js'>\x3C/script>")</script>

	<?php /* Facebook Support, at some point *//*if ($this->isHomepage) { ?>

	<meta property="og:title" content="SteamAlerts.com"/>
	<meta property="og:type" content="website"/>
	<meta property="og:url" content="http://steamalerts.com"/>
	<meta property="og:image" content="http://steamalerts.com/img/fblogo.png"/>
	<meta property="og:site_name" content="SteamAlerts"/>
	<meta property="fb:admins" content="500035730"/>
	<meta property="og:description" content="<?php echo $this->metaDesc ?>"/>

	<?php }*/ ?>

</head>
<body>
<div id="container">
    <header>
 		<h1><a href="/"><?= $title ?></a></h1>
		<ul id="typemenu">
			<li><a href="/video/1">Videos</a></li>
			<li><a href="/image/1">Images</a></li>
			<li><a href="/audio/1">Audio</a></li>
			<li><a href="/post/1">Posts</a></li>
			<li><a href="/link/1">Links</a></li>
		</ul>
    </header>

    <?php
    /** @var $this _Response */
    $flashes = $this->flashes();
    if ($flashes) {
        var_dump($flashes);
    }
    ?>

    <div id="main" role="main">
