<?php if (!defined('DISQUS_SHORTNAME')){ return; } ?>

<div id="disqus_thread"></div>

<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<?= DISQUS_SHORTNAME ?>'; // required: replace example with your forum shortname
    var disqus_identifier = '<?= isset($this->item['dqid']) ? $this->item['dqid'] : $this->item['createdAt'] ?>';
    var disqus_developer = 1;

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>