<?php $this->render('_head.phtml', array('title'=> ($this->editing ? 'Edit' : 'Create'))) ?>

<h2>Item List</h2>
<p>New: <?php foreach (getItemClasses() as $type) { ?>
    <a href="/edit/<?= $type ?>"><?= ucfirst($type) ?></a>
<?php } ?></p>

<?php if (count($this->errors)) {?>
    <div class="postcontent">Errors: <ol><li><?= implode('</li><li>', $this->errors) ?></li></ol></div>
<?php } ?>

<?php //var_dump($this->_viewvars) ?>

<table id="editlist">
    <thead>
        <tr>
            <th>Date</th>
            <th>Item Title</th>
        </tr>
    </thead>
    <tbody>

    <?php if (!isset($this->items) || count($this->items) == 0) { ?>
        <tr>
            <td colspan="3">No Items Yet</td>
        </tr>
    <?php } else { ?>
        <?php foreach ($this->items as $idx => $item) { ?>
            <tr>
                <td><?= date('Y-m-d', $item['createdAt']); ?></td>
                <td><a href="/edit/<?= $this->escape($item['type']); ?>/<?= $this->escape($item['slug']); ?>">
                    <?= $this->escape($item['title']); ?>
                </a></td>
            </tr>
        <?php } ?>
    <?php } ?>

    </tbody>
</table>

<?php

// pagination!
$linkprefix = '/edit/';
$items = paginate($user_params=array(
    'cur_page'        => $this->page,
    'total_results'   => $this->total, // should be INT
    'per_page'        => $this->perpage,
    'format'          =>  '<a href="'. $linkprefix .'{P}">{Pt}</a>',
));

if (count($items)) {
    echo '<ul class="pagi"><li>'. implode('</li><li>', $items) .'</li></ul>';
}

?>

<?php $this->render('_footer.phtml') ?>