<h3><?= $this->item['title'] ?></h3>
<div class="postAudio">
    <embed type="application/x-shockwave-flash"
           flashvars="audioUrl=<?= $this->item['url'] ?>"
           src="http://www.google.com/reader/ui/3523697345-audio-player.swf"
           width="400" height="27" quality="best"></embed>
</div>
<div class="postContent"><?= $this->item['comment'] ?></div>
<div class="date"><?= date('Y-m-d', $this->item['createdAt']) ?></div>