<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php

        $title = defined('TITLE') ? TITLE : 'Tumblite';
        echo isset($this->title) ? $this->title . ' -- ' . TITLE : TITLE;

    ?></title>
	<link rel="stylesheet" href="/css/style.css" />
</head>
<body>
<div id="container">
    
    <header>
 		<h1><a href="/"><?= $title ?></a></h1>
		<ul id="typemenu">
			<li><a href="/video/1">Videos</a></li>
			<li><a href="/status/1">Status</a></li>
			<li><a href="/image/1">Images</a></li>
			<li><a href="/audio/1">Audio</a></li>
			<li><a href="/post/1">Posts</a></li>
			<li><a href="/link/1">Links</a></li>
		</ul>
    </header>

    <?php
    /** @var $this _Response */
    $flashes = $this->flashes();
    if ($flashes) {
        var_dump($flashes);
    }
    ?>

    <div id="main" role="main">
