<?php if (!$this->bm) $this->render('_head.phtml', array('title'=> ($this->editing ? 'Edit' : 'Create'))) ?>

<?php if (!$this->bm) { ?>
    <h2><a href="/edit">All Items</a>: <?= $this->editing ? 'Edit' : 'Create' ?> <?= ucfirst($this->type) ?> Item</h2>
    <p>New: <?php foreach (getItemClasses() as $type) { ?>
        <a href="/edit/<?= $type ?>"><?= ucfirst($type) ?></a>
    <?php } ?></p>
<?php } ?>

    <?php if (count($this->errors)) {?>
        <div class="postcontent">Errors: <ol><li><?= implode('</li><li>', $this->errors) ?></li></ol></div>
    <?php } ?>

    <?php // var_dump($this->_viewvars) ?>

    <form id="edit" action="/edit/<?= $this->type ?><?= $this->itemId ? '/' . $this->itemId : '' ?>" method="POST" enctype="multipart/form-data">

        <?php

        function value($field, $itemDetails=null) {
            if (isset($_POST[$field])) {
                return $_POST[$field];
            }
            elseif (isset($itemDetails[$field])) {
                return $itemDetails[$field];
            }
            else {
                return '';
            }
        }

        foreach ($this->fields as $field) {

            switch ($field['type']) {

                case Form::TYPE_LONGTEXT:
                    ?>

                    <p>
                        <label><?= isset($field['label']) ? $field['label'] : $field['id'] ?><br/>
                            <textarea rows="15" cols="40" name="<?= $field['id'] ?>"><?= $this->escape(value($field['id'], $this->itemDetails)) ?></textarea>
                        </label><br/>

                        <label>Format: 
                            <select name="format_<?= $field['id'] ?>">
                                <?php foreach (Form::$formats as $option) { ?>

                                <option<?= value('format_'.$field['id'], $this->itemDetails) == $option ? ' selected' : '' ?>><?= $option ?></option>

                                <?php }?>
                            </select>
                        </label>
                    </p>

                    <?php
                    break;

                case Form::TYPE_CHOICE:
                    ?>

                    <p>
                        <label><?= isset($field['label']) ? $field['label'] : $field['id'] ?><br/>
                            <select name="<?= $field['id'] ?>">
                                <?php foreach ($field['options'] as $option) { ?>

                                <option<?= value($field['id'], $this->itemDetails) == $option ? ' selected' : '' ?>><?= $option ?></option>

                                <?php }?>
                            </select>
                        </label>
                    </p>

                    <?php
                    break;

                case Form::TYPE_TEXT:
                    ?>

                    <p>
                        <label><?= isset($field['label']) ? $field['label'] : $field['id'] ?><br/>
                            <input type="text" name="<?= $field['id'] ?>" value="<?= $this->escape(value($field['id'], $this->itemDetails)) ?>" />
                        </label>
                    </p>

                    <?php
                    break;

                case Form::TYPE_IMAGEUPLOAD:
                    ?>

                    <p>
                        <?= isset($field['label']) ? $field['label'] : $field['id'] ?><br/>
                            <input type="file" name="file_<?= $field['id'] ?>" />
                            or url: <input type="text" name="url_<?= $field['id'] ?>" value="<?= $this->escape(value('url_'.$field['id'], $this->itemDetails)) ?>" /><br/>
                            <em>File Upload will take precedence if both are filled in</em>
                            <?php
                            $current = value($field['id'], $this->itemDetails);
                            if (!empty($current)) {
                                echo '<br/><input type="hidden" name="cur_'. $field['id'] .'" value="'. $current .'" />Current: ' . $current;
                            }
                            ?>

                    </p>

                    <?php
                    break;

                case Form::TYPE_URL:
                    ?>

                    <p>
                        <label><?= isset($field['label']) ? $field['label'] : $field['id'] ?><br/>
                            <input type="text" name="<?= $field['id'] ?>" value="<?= $this->escape(value($field['id'], $this->itemDetails)) ?>" />
                        </label>
                    </p>

                    <?php
                    break;

            }
        }

        ?>



        <div style="float: left">
            <input type="submit" value="  Save  " />
            <label><input type="checkbox" name="_is_static" value="1" <?= value('_is_static', $this->itemDetails) == 1 ? 'checked' : '' ?> /> Exclude from post lists?</label>
        </div>

        <?php if ($this->editing) { ?>
            <input type="submit" name="delete" value="Delete" style="float: right"/>
        <?php } ?>
        
        <?php if ($this->bm) { ?>
            <input type="hidden" name="bm" value="1" />
        <?php } ?>
    </form>

<?php if (!$this->bm) $this->render('_footer.phtml') ?>