<?php if (!$this->bm) $this->render('_head.phtml', array('title'=> ($this->editing ? 'Edit' : 'Create'))) ?>

	<h2><?= $this->editing ? 'Edit' : 'Create' ?> <?= $this->type ?></h2>

    <?php if (count($this->errors)) {?>
        <p>Errors: <br/><br/><?= implode('<br/>', $this->errors) ?></p>
    <?php } ?>

    <?php // var_dump($this->_viewvars) ?>

    <form action="/edit/<?= $this->type ?><?= $this->itemId ? '/' . $this->itemId : '' ?>" method="POST" enctype="multipart/form-data">

        <?php

        function value($field, $itemDetails=null) {
            if (isset($_POST[$field])) {
                return $_POST[$field];
            }
            elseif (isset($itemDetails[$field])) {
                return $itemDetails[$field];
            }
            else {
                return '';
            }
        }

        foreach ($this->fields as $field) {

            switch ($field['type']) {

                case Form::TYPE_POSTPROCESS:
                    // we skip this one
                    break;

                case Form::TYPE_LONGTEXT:
                    ?>

                    <p>
                        <label><?= $field['id'] ?><br/>
                            <textarea rows="15" cols="40" name="<?= $field['id'] ?>"><?= $this->escape(value($field['id'], $this->itemDetails)) ?></textarea>
                        </label><br/>

                        <label>Format: 
                            <select name="format_<?= $field['id'] ?>">
                                <?php foreach (Form::$formats as $option) { ?>

                                <option<?= value('format_'.$field['id'], $this->itemDetails) == $option ? ' selected' : '' ?>><?= $option ?></option>

                                <?php }?>
                            </select>
                        </label>
                    </p>

                    <?php
                    break;

                case Form::TYPE_CHOICE:
                    ?>

                    <p>
                        <label><?= $field['id'] ?><br/>
                            <select name="<?= $field['id'] ?>">
                                <?php foreach ($field['options'] as $option) { ?>

                                <option<?= value($field['id'], $this->itemDetails) == $option ? ' selected' : '' ?>><?= $option ?></option>

                                <?php }?>
                            </select>
                        </label>
                    </p>

                    <?php
                    break;

                case Form::TYPE_TEXT:
                    ?>

                    <p>
                        <label><?= $field['id'] ?><br/>
                            <input type="text" name="<?= $field['id'] ?>" value="<?= $this->escape(value($field['id'], $this->itemDetails)) ?>" />
                        </label>
                    </p>

                    <?php
                    break;

                case Form::TYPE_IMAGEUPLOAD:
                    ?>

                    <p>
                        <?= $field['id'] ?><br/>
                            <input type="file" name="file_<?= $field['id'] ?>" />
                            or url: <input type="text" name="url_<?= $field['id'] ?>" value="<?= $this->escape(value('url_'.$field['id'], $this->itemDetails)) ?>" /><br/>
                            <em>File Upload will take precedence if both are filled in</em>
                            <?php
                            $current = value($field['id'], $this->itemDetails);
                            if (!empty($current)) {
                                echo '<br/><input type="hidden" name="cur_'. $field['id'] .'" value="'. $current .'" />Current: ' . $current;
                            }
                            ?>

                    </p>

                    <?php
                    break;

                case Form::TYPE_URL:
                    ?>

                    <p>
                        <label><?= $field['id'] ?><br/>
                            <input type="text" name="<?= $field['id'] ?>" value="<?= $this->escape(value($field['id'], $this->itemDetails)) ?>" />
                        </label>
                    </p>

                    <?php
                    break;

            }
        }

        ?>

        <input type="submit" value="  Save  " /> <label><input type="checkbox" name="_is_static" value="1" <?= value('_is_static', $this->itemDetails) == 1 ? 'checked' : '' ?> /> Exclude from post lists?</label>
        <hr/>
        <input type="submit" name="delete" value="Delete" />
    </form>

<?php if (!$this->bm) $this->render('_footer.phtml') ?>