<?php if (defined('DISQUS_SHORTNAME') && DISQUS_SHORTNAME ) { ?>
	<script type="text/javascript">
		var disqus_shortname = '<?= DISQUS_SHORTNAME ?>';
		var disqus_developer = 1;
		(function () {
			var s = document.createElement('script'); s.async = true;
			s.type = 'text/javascript';
			s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
			(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
		})();
	</script>
<?php } ?>