
<div class="item item-<?= $this->item['type'] ?>">

    <?php

    $view = VIEWDIR.'item_'. $this->item['type'] .'.phtml';
    if (file_exists($view)) {
        $this->render($view, array('item'=>$this->item));
    }
    else {
        echo '<p>Unknown Post Type</p>';
        var_dump($item);
    }

    ?>

    <p><a href="/edit/<?= $this->item['type'] ?>/<?= $this->item['slug'] ?>">Edit</a></p>
    <p><a href="/<?= $this->item['slug'] ?>">Link</a></p>

</div>
