<h2><?= $this->item['title'] ?></h2>

<div class="postVideo"><?php

$url = parse_url($this->item['url']);
$params = array();
if (!empty($url['query'])) {
    parse_str($url['query'], $params);
}

if (strpos($url['host'], 'youtube') !== false) {
    echo '<iframe width="640" height="510" src="http://www.youtube.com/embed/'. $params['v'] .'" frameborder="0" allowfullscreen></iframe>';
}
elseif (strpos($url['host'], 'vimeo') !== false) {
    echo '<iframe src="http://player.vimeo.com/video'. $url['path'] .'" width="640" height="360" frameborder="0"></iframe>';
}

?></div>

<div class="postcontent"><?= $this->item['commentRendered'] ?></div>