<?php $this->render('_head.phtml') ?>

<!--<h2>--><?//= ucfirst($this->list) ?><!-- items, page --><?//= $this->page ?><!--</h2>-->

<?php

//var_dump($this->list);
//var_dump($this->page);
//var_dump($this->start);
//var_dump($this->end);
//var_dump($this->items);

//var_dump(isset($this->items));
//var_dump(count($this->items));
//var_dump($this->items);

if(isset($this->items) && count($this->items)) {
    foreach ($this->items as $item) {
        $this->render('item.phtml', array('item'=>$item));
    }

    // pagination!
    $linkprefix = ($this->list == 'all' ? '/' : '/' . $this->list . '/');
    $items = paginate($user_params=array(
        'cur_page'        => $this->page,
        'total_results'   => $this->total, // should be INT
        'per_page'        => PERPAGE,
        'format'          =>  '<a href="'. $linkprefix .'{P}">{Pt}</a>',
    ));

    if (count($items)) {
        echo '<ul class="pagi"><li>'. implode('</li><li>', $items) .'</li></ul>';
    }
    
}
else {
    echo '
    <center>
        <p>There are no '. $this->list .' items yet.</p>
        <p>' . ( hasAuth() ?
            '<a href="/edit/'. $this->list . '">Create a new '. ucfirst($this->list) . ' item</a>.'
          : '<a href="/auth/login">Login</a> to create new posts.'
        ) . '</p>
    </center>
    ';
}

?>

<?php $this->render('_footer.phtml') ?>