<?php $this->render('_head.phtml') ?>

<!--<h2>--><?//= ucfirst($this->list) ?><!-- items, page --><?//= $this->page ?><!--</h2>-->

<?php

//var_dump($this->list);
//var_dump($this->page);
//var_dump($this->start);
//var_dump($this->end);
//var_dump($this->items);

//var_dump(isset($this->items));
//var_dump(count($this->items));
//var_dump($this->items);

if(isset($this->items) && count($this->items)) {
    foreach ($this->items as $item) {
        $this->render('item.phtml', array('item'=>$item));
    }
}
else {
    echo '<p>There are no '. $this->list .' items yet.</p>';
}

?>

<?php $this->render('_footer.phtml') ?>